# -*- coding: utf-8 -*-
"""machinelearning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y6CJkLlV2QWnmxGjLJFH52eqZQnSkvrD
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.cluster import KMeans
from sklearn.metrics import r2_score

sns.set_style("whitegrid")


file_path = "housingPrice.csv"
data = pd.read_csv(file_path)


keterangan = {
    "median_house_value": "Harga rumah",
    "total_rooms": "Luas bangunan",
    "total_bedrooms": "Jumlah kamar tidur"
}

model_regresi = None


def tampil_dataset():
    print("\nKETERANGAN KOLOM")
    for kolom in data.columns:
        if kolom in keterangan:
            print(kolom, ":", keterangan[kolom])
        else:
            print(kolom, ": Tidak ada deskripsi")

    print("\n5 DATA TERATAS")
    print(data.head())

    print("\n5 DATA TERAKHIR")
    print(data.tail())


def visualisasi_data():
    print("\nVISUALISASI DATA")

    plt.figure(figsize=(6,4))
    sns.histplot(data["median_house_value"], bins=30, kde=True)
    plt.title("Distribusi Harga Rumah")
    plt.xlabel("Harga")
    plt.ylabel("Jumlah")
    plt.show()

    plt.figure(figsize=(6,4))
    sns.scatterplot(x="total_rooms", y="median_house_value", data=data)
    plt.title("Hubungan Luas Rumah dan Harga")
    plt.xlabel("Luas Rumah")
    plt.ylabel("Harga")
    plt.show()

    plt.figure(figsize=(6,4))
    sns.boxplot(x="total_bedrooms", y="median_house_value", data=data)
    plt.title("Harga Rumah Berdasarkan Jumlah Kamar Tidur")
    plt.show()


def machine_learning():
    global model_regresi

    fitur = ["total_rooms", "total_bedrooms"]
    X = data[fitur].copy()
    y = data["median_house_value"]


    for col in X.columns:
        if X[col].isnull().any():
            median_val = X[col].median()
            X[col] = X[col].fillna(median_val)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    model_regresi = LinearRegression()
    model_regresi.fit(X_train, y_train)

    skor = r2_score(y_test, model_regresi.predict(X_test))

    print("\nMODEL REGRESI BERHASIL DILATIH")
    print("R2 Score:", round(skor, 3))


def prediksi_harga():
    if model_regresi is None:
        print("Model belum dilatih!")
        print("Silakan jalankan menu Machine Learning terlebih dahulu.")
        return

    print("\nMASUKKAN DATA RUMAH")

    total_rooms = int(input("Luas rumah (total rooms): "))
    total_bedrooms = int(input("Jumlah kamar tidur (total bedrooms): "))


    data_input = pd.DataFrame(
        [[total_rooms, total_bedrooms]],
        columns=["total_rooms", "total_bedrooms"]
    )

    hasil = model_regresi.predict(data_input)

    print("\nHASIL PREDIKSI")
    print("Perkiraan Harga Rumah: Rp", int(hasil[0]))


def clustering_rumah():
    X_cluster = data[["total_rooms", "median_house_value"]].copy()


    for col in X_cluster.columns:
        if X_cluster[col].isnull().any():
            median_val_cluster = X_cluster[col].median()
            X_cluster[col] = X_cluster[col].fillna(median_val_cluster)

    kmeans = KMeans(n_clusters=3, random_state=42, n_init='auto')
    data["cluster"] = kmeans.fit_predict(X_cluster)

    plt.figure(figsize=(6,4))
    sns.scatterplot(
        x="total_rooms",
        y="median_house_value",
        hue="cluster",
        palette="Set1",
        data=data
    )
    plt.title("Clustering Rumah Berdasarkan Harga & Luas")
    plt.show()


def cari_rumah():
    print("\nMASUKKAN KRITERIA PENCARIAN")

    min_total_rooms = int(input("Minimal luas rumah (total rooms): "))
    max_median_house_value = int(input("Harga maksimal (median house value): "))

    hasil = data[
        (data["total_rooms"] >= min_total_rooms) &
        (data["median_house_value"] <= max_median_house_value)
    ]

    print("\nHASIL PENCARIAN")
    print(hasil[["total_rooms", "total_bedrooms", "median_house_value"]].head())


while True:
    print("\nMENU PROGRAM")
    print("1. Tampilkan Dataset")
    print("2. Visualisasi Data")
    print("3. Machine Learning (Latih Model)")
    print("4. Prediksi Harga Rumah")
    print("5. Clustering Rumah")
    print("6. Cari Rumah Sesuai Kriteria")
    print("0. Keluar")

    pilihan = input("Pilih menu: ")

    if pilihan == "1":
        tampil_dataset()
    elif pilihan == "2":
        visualisasi_data()
    elif pilihan == "3":
        machine_learning()
    elif pilihan == "4":
        prediksi_harga()
    elif pilihan == "5":
        clustering_rumah()
    elif pilihan == "6":
        cari_rumah()
    elif pilihan == "0":
        print("Program selesai")
        break
    else:
        print("Pilihan tidak valid")
